const images={
  Splash_image: require('./Images/logo.png'),
  Splash_image2: require('./Images/moving_car.gif'),
  bg_image: require('./Images/bg1.png'),
  menu_bar: require('./Images/menubar.png'),
  white_bar: require('./Images/white_bar.png'),
  Search_bar: require('./Images/search.png'),
  round: require('./Images/round.png'),
  round_red: require('./Images/round_red.png'),
  remove: require('./Images/remove.png'),
  remove_white: require('./Images/remove_white.png'),
  home: require('./Images/home.png'),
  notify: require('./Images/notify.png'),
  Account: require('./Images/Account.png'),
  bid: require('./Images/bid.png'),
  lists: require('./Images/file.png'),
  Portal: require('./Images/portal.png'),
  Purchase: require('./Images/purchase.png'),
  acc_file: require('./Images/acc_file.png'),
  stock: require('./Images/stock.png'),
  sort: require('./Images/sort.png'),
  profile: require('./Images/profile.png'),
  ribbon: require('./Images/ribbon.png'),
  ribbon2: require('./Images/ribbon2.png'),
  ribbon3: require('./Images/ribbon3.png'),
  ribbon4: require('./Images/ribbon4.png'),
  back: require('./Images/back.png'),
  down: require('./Images/down.png'),
  white_box: require('./Images/white_box.png'),
  red_box: require('./Images/red_box.png'),
  sortdown: require('./Images/sortdown.png'),
  white_ribbon: require('./Images/white_ribbon.png'),
  calender: require('./Images/calendar.png'),
  download: require('./Images/download.png'),
  down2: require('./Images/down2.png'),
  filter: require('./Images/filter.png'),
  bblack: require('./Images/bblack.png'),
  bblack2: require('./Images/bblack2.png'),
  bdown: require('./Images/bdown.png'),
  bdown3: require('./Images/bdown3.png'),
check: require('./Images/check.png'),
latest: require('./Images/latest.png'),
archive: require('./Images/archive.png'),
clear: require('./Images/clear.png'),
 dot:require('./Images/3dots.png'),
 logout:require('./Images/logout.png'),
 settings:require('./Images/settings.png'),
 delete:require('./Images/delete.png'),
 share:require('./Images/share.png'),
 sort2:require('./Images/sort2.png'),
 less:require('./Images/less.png'),
 greater:require('./Images/greater.png'),
 
 img:require('./Images/img.png'),
 wink:require('./Images/wink.png'),
 eyeopen:require('./Images/eyeopen.png'),
 eyeclose:require('./Images/eyeclose.png'),
 noimage:require('./Images/noimage.png'),
 morethan:require('./Images/morethan.png'),
 edit:require('./Images/edit.png'),
 whatsapp:require('./Images/whtsapp.png'),
 homebg:require('./Images/homebg.png'),
 homebg1:require('./Images/homebg1.png'),
 homebg2:require('./Images/homebg2.png'),
 car:require('./Images/car18.png'),
 boxbg:require('./Images/boxbg.png'),
grid:require('./Images/grid.png'),
boxbg1:require('./Images/boxbg1.png'),
uup:require('./Images/ddown.png'),
ddown:require('./Images/uup.png'),
drawerdot:require('./Images/drawerdot.png'),
bookbg:require('./Images/bookbg.png'),
loginbook:require('./Images/loginbook.png'),
sbook:require('./Images/sbook.png')

};

// eslint-disable-next-line prettier/prettier
export default images
